#4 More changes to ensure UI tests work in Jenkins pipeline.
 - Using the 'centos-7' pod template was not enough.
   - It solved the NoClassDefFoundError for SWT Display class.
   - Which solved the hanging Chi test.
   - Chi tests were now successful.
 - Subsequently, now the CIF tests failed.
   - Now using Xvnc plugin to ensure display is actually available.
   - This will hopefully make the CIF tests successful as well.